before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - id: operator-controller
    main: ./cmd/operator-controller/
    binary: operator-controller
    asmflags: "{{ .Env.GO_BUILD_ASMFLAGS }}"
    gcflags: "{{ .Env.GO_BUILD_GCFLAGS }}"
    ldflags: "{{ .Env.GO_BUILD_LDFLAGS }}"
    tags:
      - "{{ .Env.GO_BUILD_TAGS }}"
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x
  - id: catalogd
    main: ./cmd/catalogd/
    binary: catalogd
    asmflags: "{{ .Env.GO_BUILD_ASMFLAGS }}"
    gcflags: "{{ .Env.GO_BUILD_GCFLAGS }}"
    ldflags: "{{ .Env.GO_BUILD_LDFLAGS }}"
    tags:
      - "{{ .Env.GO_BUILD_TAGS }}"
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  use: github
  disable: '{{ ne .Env.ENABLE_RELEASE_PIPELINE "true" }}'
  groups:
    - title: Dependency Bumps
      regexp: '^:seedling: Dependabot:.*$'
      order: 0
release:
  disable: '{{ ne .Env.ENABLE_RELEASE_PIPELINE "true" }}'
  mode: replace
  extra_files:
    - glob: '{{ .Env.STANDARD_RELEASE_MANIFEST }}'
    - glob: '{{ .Env.STANDARD_RELEASE_INSTALL }}'
    - glob: '{{ .Env.EXPERIMENTAL_RELEASE_MANIFEST }}'
    - glob: '{{ .Env.EXPERIMENTAL_RELEASE_INSTALL }}'
    - glob: '{{ .Env.RELEASE_CATALOGS }}'
  header: |
    ## Installation

    ```bash
    curl -L -s https://github.com/operator-framework/operator-controller/releases/download/{{ .Tag }}/install.sh | bash -s
    ```
