apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: catalogd-controller-manager-metrics-monitor
  namespace: system
spec:
  endpoints:
    - path: /metrics
      port: metrics
      interval: 10s
      scheme: https
      authorization:
        credentials:
          name: prometheus-metrics-token
          key: token
      tlsConfig:
        # NAMESPACE_PLACEHOLDER replaced by replacements in kustomization.yaml
        serverName: catalogd-service.NAMESPACE_PLACEHOLDER.svc
        insecureSkipVerify: false
        ca:
          secret:
            # CATALOGD_SERVICE_CERT must be replaced by envsubst
            name: ${CATALOGD_SERVICE_CERT}
            key: ca.crt
        cert:
          secret:
            name: ${CATALOGD_SERVICE_CERT}
            key: tls.crt
        keySecret:
          name: ${CATALOGD_SERVICE_CERT}
          key: tls.key
  selector:
    matchLabels:
      app.kubernetes.io/name: catalogd
