name: go-apidiff
on:
  push:
  workflow_dispatch:
  merge_group:
  pull_request:
jobs:
  go-apidiff:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - uses: dtfranz/go-apidiff@test-pkg-exception
      with:
        base-ref: 3d6a33b60dab6aedec2b676eba3a7631d3961340
